[ms2rescore]
psm_file = "examples/data/search/sage/results.sage.tsv"
psm_file_type = "sage"
spectrum_path = "examples/data/spectra/qExactive01819.mzML"

[ms2rescore.feature_generators]
"basic" = {}
"ms2pip" = { "model" = "HCD" }
"ms2" = {}
"deeplc" = {}
